### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by veggiesaurus** [drizzt/GaiaManager#18]
A few tiny mistakes with the English translation that I've picked up (from reading i18n.h):

-text_launcher: should be "You can launch this utility <b>by</b> pressing SELECT+START the next time"
-text_cover_msg: should be "Do you want to download missing covers (in /dev_hdd0/" COVERS_DIR ")?\nIt could <b>take<\b> awhile...\nPlease wait"

**Comment by drizzt** [comment]
Fixed, thanks
